### ISSUE TITLE
Can't locate object method "render_text" via package "Mojolicious::Controller" at ./mojowka line 471.

### ISSUE THREAD

**Issue by szabgab** [shoorick/mojowka#5]
Clicking on the "Logged as admin" link I get to http://localhost:3000/profile/admin
where I get the error 

Can't locate object method "render_text" via package "Mojolicious::Controller" at ./mojowka line 471.

$ mversion Mojolicious
4.19

**Comment by dastier** [comment]
I began to study Mojolicious and got the same. I have to use render(text => ...) instead of render_text(...)

**Comment by Sword-Smith** [comment]
dastier: That worked for me. Thank you!

**Comment by shoorick** [comment]
Thank you and sorry for my bad responsibility.
